/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

/**
 *
 * @author Joabp
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    private String[][] s = {
        {"Revisar la corriente y la fuente", "Revisad que el cable de la fuente esté bien conectado y que el botón de la misma esté en «on«. Para curarnos en salud, cambiad el cable de la fuente y volver a probar. Como veis, en principio, esto es un ensayo-error hasta que demos con el problema."},
        {"Revisad las conexiones de la fuente a la placa", "Toca abrir la caja para revisar todas las conexiones relacionadas con el suministro de electricidad por parte de la fuente y placa base. No sólo eso, también tenéis que revisar las conexiones de la caja a la placa base; de hecho, este suele ser uno de los problemas comunes por los que el PC no enciende."},
        {"Comprueba que la memoria RAM esté bien conectada", "Suele ocurrirle a mucha gente; de hecho, le ocurrió a un servidor. Puede que las memorias estén mal conectadas o algún slot concreto esté dañado. Por tanto, probad a cambiarlas de sitio o revisad que estén bien acopladas. Puede ser la razón por la que no la que el PC no arranca, así que la ponemos entre las soluciones."},
        {"Pila CMOS", "La pila CMOS tiene un papel muy importante en cuanto a la energía de la placa base. Podemos encontrarnos con muchos casos diferentes: ranura de la pila rota, pila agotada, conflicto en la BIOS, etc. En primer lugar, probad a quitar la pila, esperar 1 minuto y volver a instalarla. Con esto, encended el PC a ver si se ha solucionado. Si no es así y tenéis otro PC cerca, cambiad las pilas CMOS y probad otra vez. Si la del PC que no arranca funciona en el otro PC, significa que no es el problema. El hecho de que esté la ranura de esta pila rota, tiene una importancia vital, pero reconocemos que es muy complicado que se dé el caso. También, es importante insertar la pila en la forma correcta, así que consultad en el manual de la placa hacia dónde tiene que estar el polo positivo/negativo."},
        {"Desconecta dispositivos externos", "Llegados a este punto, vamos a intentar quitar todos los dispositivos externos, como pueden ser los periféricos o cualquier disco duro o pendrive conectado. Puede que alguno esté provocando un conflicto; es poco probable que ocurra esto, pero se han dado casos rarísimos en los que ha pasado esto. Intentad desconectar todos menos el teclado, el cual es imprescindible para manejarnos por la BIOS aunque sea."},
        {"Voltaje de país diferente", "Podemos encontrarnos con la problemática de que nos hayamos mudado a un país nuevo en el que se utilice otro voltaje distinto. En la fuente podéis averiguar su voltaje; después, consultad qué voltaje hay en la instalación de vuestra casa."},
        {"Fuente, placa base, CPU o GPU dañada", "Si habéis llegado a este punto y vuestro PC sigue sin arrancar… mal asunto. Puede que haya componentes dañados, como es el caso de la fuente o placa base. Yo os recomendaría cambiar de fuente de alimentación y volver a probar para ver si es ésta la culpable. Puede que algún cable no funcione bien o haya algún problema con la fuente."}
    };
    private int x;

    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
        respueta.setWrapStyleWord(true);
        respueta.setLineWrap(true);
        respueta.setEditable(false);
        funcionoBtn.setVisible(false);
        noFuncionoBtn.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoPanel = new javax.swing.JPanel();
        resultadoPanel = new javax.swing.JPanel();
        tituloRespuesta = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        respueta = new javax.swing.JTextArea();
        empezarBtn = new javax.swing.JButton();
        tituloLabel = new javax.swing.JLabel();
        funcionoBtn = new javax.swing.JButton();
        noFuncionoBtn = new javax.swing.JButton();
        imagenFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondoPanel.setMinimumSize(new java.awt.Dimension(600, 400));
        fondoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        resultadoPanel.setBackground(new java.awt.Color(255, 255, 255));
        resultadoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        resultadoPanel.add(tituloRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, -1));

        respueta.setColumns(20);
        respueta.setRows(5);
        jScrollPane1.setViewportView(respueta);

        resultadoPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 330, 170));

        fondoPanel.add(resultadoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 330, 190));

        empezarBtn.setText("Empezar");
        empezarBtn.setPreferredSize(new java.awt.Dimension(100, 25));
        empezarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empezarBtnActionPerformed(evt);
            }
        });
        fondoPanel.add(empezarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 100, -1));

        tituloLabel.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(255, 255, 255));
        tituloLabel.setText("Sistema Experto");
        fondoPanel.add(tituloLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        funcionoBtn.setText("Funciono");
        funcionoBtn.setPreferredSize(new java.awt.Dimension(100, 25));
        funcionoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funcionoBtnActionPerformed(evt);
            }
        });
        fondoPanel.add(funcionoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        noFuncionoBtn.setText("No funciono");
        noFuncionoBtn.setPreferredSize(new java.awt.Dimension(100, 25));
        noFuncionoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noFuncionoBtnActionPerformed(evt);
            }
        });
        fondoPanel.add(noFuncionoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, -1, -1));

        imagenFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.jpg"))); // NOI18N
        fondoPanel.add(imagenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(fondoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void empezarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empezarBtnActionPerformed
        x = 0;
        recorrerMAtriz(x++);
        funcionoBtn.setVisible(true);
        noFuncionoBtn.setVisible(true);
        empezarBtn.setVisible(false);
    }//GEN-LAST:event_empezarBtnActionPerformed

    private void noFuncionoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noFuncionoBtnActionPerformed
        recorrerMAtriz(x++);
    }//GEN-LAST:event_noFuncionoBtnActionPerformed

    private void funcionoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcionoBtnActionPerformed
        tituloRespuesta.setText(" ");
        respueta.setText("Gracias por usar nuestro sistema experto");
        funcionoBtn.setVisible(false);
        noFuncionoBtn.setVisible(false);
        empezarBtn.setVisible(true);
    }//GEN-LAST:event_funcionoBtnActionPerformed

    private void recorrerMAtriz(int x) {
        if (x < 7) {
            tituloRespuesta.setText(s[x][0]);
            respueta.setText(s[x][1]);
        } else {
            tituloRespuesta.setText(" ");
            respueta.setText("Gracias por usar nuestro sistema experto");
            funcionoBtn.setVisible(false);
            noFuncionoBtn.setVisible(false);
            empezarBtn.setVisible(true);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton empezarBtn;
    private javax.swing.JPanel fondoPanel;
    private javax.swing.JButton funcionoBtn;
    private javax.swing.JLabel imagenFondo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton noFuncionoBtn;
    private javax.swing.JTextArea respueta;
    private javax.swing.JPanel resultadoPanel;
    private javax.swing.JLabel tituloLabel;
    private javax.swing.JLabel tituloRespuesta;
    // End of variables declaration//GEN-END:variables
}
